### ISSUE TITLE
How to config 2 players in one keyboard ?

### ISSUE THREAD

**Issue by richard42** [mupen64plus/mupen64plus-user-issues#572]
Originally reported on Google Code with ID 573

```
System:
 - Operating System (be specific): Ubuntu 12.04
 - Machine type (32-bit or 64-bit): 32
 - Mupen64Plus version: 1.99.4

Hello Guys, (Sorry, my english really sucks)

I'm trying to play Super Smash Bros with my brother, but i can't figure out how to
configure an additional [Keyboard] or something like this for play in multiplayer mode.
Sorry for the mistakes!
and thanks :)

```

Reported by `victorsp2153` on 2013-08-07 01:49:36

**Comment by richard42** [comment]
```
https://code.google.com/p/mupen64plus/wiki/FileLocations
https://code.google.com/p/mupen64plus/wiki/KeyboardSetup
https://code.google.com/p/mupen64plus/wiki/ControllerSetup
https://code.google.com/p/mupen64plus/wiki/InputPluginUsage
```

Reported by `sven@narfation.org` on 2013-08-07 09:31:32
- **Status changed**: `Invalid`

**Comment by Domarius** [comment]
Actually the OP was asking about having 2 players on one keyboard.  The linked pages only tell you how to set up one player on one keyboard.

If this isn't possible, we should specifically state that.

I'm looking into this personally since I 'm setting up my own arcade machine with the joysticks mapped to an IPAC which simulates a keyboard.
