### ISSUE TITLE
Xbox ONE Controller config (request)

### ISSUE THREAD

**Issue by Kaito-RTRT** [mupen64plus/mupen64plus-user-issues#665]
I use mupen64plus under linux. Latest kernel supports XBOX ONE controller. So please add config for XBOX ONE controller to ini file. M64py has a bug and cannot save input config. Now it's not easy to set proper key codes. Regards.

**Comment by zmertens** [comment]
I think I have run into a similar issue on Linux Mint with the XBOX 360 controller. I went into ~/.config/mupen64plus/mupen64plus.cfg to try to change the default controller settings but they do not appear to stick. I have used Mupen64plus 2.0 before on Ubuntu and did not run into this issue. So I'm not sure if the issue is Linux Mint or Mupen64plus 2.5 which is what I'm currently using.

**Comment by richard42** [comment]
Zach, you have to make sure that the Mode parameter is set to "2" if you want
to manually specify your own configuration.  Otherwise (with mode 0 or 1) the
auto-configuration code will overwrite the parameters.

Richard

**Comment by zmertens** [comment]
Ahh, I see what you mean @richard42 -- fixed, no issue for me now.

**Comment by richard42** [comment]
actually I wrote the wrong thing in my previous post.  The fully manual mode is 0, while the automatic modes are 1 and 2.

**Comment by FlorianLuna** [comment]
if nothing above works you can add in InputAutoCfg.ini the following config
[Xbox One Wired Controller]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
DPad R = "button(3)"
DPad L = "button(2)"
DPad D = "button(0)"
DPad U = "button(1)"
Start = "button(4)"
Z Trig = "axis(5+)"
B Button = "button(12)"
A Button = "button(11)"
C Button R = "axis(2+)"
C Button L = "axis(2-)"
C Button D = "axis(3+)"
C Button U = "axis(3-)"
R Trig = "button(9)"
L Trig = "button(8)"
Mempak switch = ""
Rumblepak switch = ""
X Axis = "axis(0-,0+)"
Y Axis = "axis(1-,1+)"
