### ISSUE TITLE
how to change controls configuration

### ISSUE THREAD

**Issue by hanielhuam** [mupen64plus/mupen64plus-user-issues#683]
i have already change my `.config/mupen64plus/mupen64plus.cfg` and chage the:
`B Button = "key(306)"`
`A Button = "key(304)"`

however, when i restart the mupen64plus it doesn`t make a difference

**Comment by richard42** [comment]
If you want to manually configure the controls in mupen64plus.cfg, make sure that you set the "mode" parameter in the Input-SDL-Control section that you're changing to "0" (fully manual).  Otherwise, the values that you set here may be overridden to their original values by the auto-configuration feature.
