### ISSUE TITLE
Inputting cheats from 'write' in debug mode of console ui

### ISSUE THREAD

**Issue by miker2049** [mupen64plus/mupen64plus-user-issues#715]
is it possible to do this?  Such that cheats could be enabled on the fly if we are just using the console UI?  I assume there is a translation of gameshark code into something more raw, but having trouble figuring that out.

**Comment by richard42** [comment]
No, this cannot be done with the current code. The "write" command in the debugger writes to the memory of the emulated N64 system. A cheat code however gets stored in the memory of the emulator, and processed by a virtual machine which is part of the emulator itself. In order to achieve this, someone would need to add new commands to the debugger UI in the mupen64plus-ui-console application, and pass the gameshark codes into the emulator via it's shared library API.
