### ISSUE TITLE
Wiki CSS appears to be broken

### ISSUE THREAD

**Issue by jgcodes2020** [mupen64plus/mupen64plus-user-issues#749]
The wiki used to be properly formatted and styled. Its CSS appears to be broken (sample from [here](https://mupen64plus.org/wiki/index.php/Mupen64Plus_v2.0_Core_Front-End)):
![image](https://github.com/user-attachments/assets/a0931b85-ea03-4059-ae1a-5b0ea2314a52)

**Comment by richard42** [comment]
I noticed this was broken quite a few months ago but knew it would be a PITA to fix... It looks like my web host now has natively supported mediawiki packages that can be installed from cpanel, so really that would be the best way to go, but it would be even more work to migrate the existing wiki onto a new one.  So I'm at home now for Christmas and don't have anything terribly important to do, so I fixed our old media wiki installation.  The problem was that using curly braces to select array elements was no longer supported in the newer version of php to which my web host upgraded.  So I just fixed all instances of that in one of the mediawiki php scripts and it looks normal again.
